[package]
name = "kinda_shell"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
chrono-tz = "0.10.4"
iana-time-zone = "0.1.63"
regex = "1.11.1"
terminal_size = "0.4.2"
users = "0.11.0"

xattr = "1.0.1"
